### PR TITLE
plutonium update

### PR DESCRIPTION
**Pull request by radhikasahai**
Adding plutonium

### CODE REVIEW

**Review by Bitbybit123 — CHANGES_REQUESTED** [review]
The description needs at least three sentences for full credit according to the grading rubric.

**Comment by parkerfromm** [comment]
The description should be atleast three sentences long.

**Comment by JedrickZablan** [comment]
Hi! Your description needs three sentences to be accepted. You just need two more facts. The rest looks good though.

**Comment by radhikasahai** [comment]
close #123

**Pull request closed without merging**
