### PR TITLE
update Gold element page

### PR DESCRIPTION
**Pull request by sneurog**
Added atomic symbol and atomic number

### CODE REVIEW

**Comment by tifanychu** [comment]
Hi, I reviewed the information about your chosen element (Gold) and made sure the information and page header is accurate!

**Review by pujamadgula — COMMENTED** [review]
Add a few lines about Gold (3 line description)!

**Comment by sneurog** [comment]
> Hi, I reviewed the information about your chosen element (Gold) and made sure the information and page header is accurate!

THANK YOU

**Review by tyc4 — APPROVED** [review]
Looks good to me

**Pull request merged**
